### ISSUE TITLE
Popup to request "Always" location permissions if not set

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#12]
For Android 10+, users need to manually allow "Always" in the app settings. When the user enables notifications through the button in the menu, and the "Always" permission is not granted, it would be really awesome if a message with the following text would appear: "To allow meteocool to notify you of incoming rain, you need to select "Always" under "Location Permissions" in the app settings." After closing the dialog, the App settings page should be opened like described here: https://stackoverflow.com/questions/32822101/how-to-programmatically-open-the-permission-screen-for-a-specific-app-on-android?rq=1

@Wheedman what do you think? A "light" version of this would be to just show the message and refuse to set the "Notifications" slider to the "on" position if the permission is not granted. That would already be better than the current solution where the user can't tell if notifications will actually work.

**Comment by Wheedman** [comment]
Solution provided.
