### ISSUE TITLE
Show error message OS location services are completely disabled

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#16]
It would be helpful if a prompt is shown...

- When tapping the locate me button
- When notifications are turned on

in case the user has location services disabled.

**Comment by Wheedman** [comment]
Fix: Locate me button considers whether location is switched on or off
Fix: If Notifications are turned on and the permission requirements are met but location is disabled in general the user will be prompted until he enables them. Maybe consider only asking a specific amount of time but I also think the user is more interested about turning it on. @v4lli Please state your opinion about that.
