### ISSUE TITLE
no location with microG

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#25]
Original issue from old monorepo at https://github.com/v4lli/meteocool/issues/194 - porting it here for completeness.

**Comment by obifur** [comment]
I can confirm this issue with Android 11.

Device: OnePlus 6
ROM: crDroid 7.11 (Android 11)
Microg: 0.2.22.212658 with several location modules ( deja VU, GSM standortdienste, mozilla location service, WLAN standortdienst)

I get location with other apps like osmand, satstat, weawow,...

**Comment by v4lli** [comment]
@obifur @nebukadneza could you try if anything changed with the latest f-droid release?

**Comment by Nebukadneza** [comment]
I can confirm that with meteocool `2.1j` and microg `0.2.22.212658`, using almost all location modules (apple wifi, dejavu, gsm location service, gsmnetworklocationprovider, merged wifi location service, mozilla, radiocells.org and wifi location service), **it is working**. I get almost instant (i.e., network location, not GPS) and correct position after starting meteocool.

Very cool, thanks a bunch!

**Comment by obifur** [comment]
YES, it's working perfectly - thank you very much!

**Comment by v4lli** [comment]
Nice, thanks for verifying! All props for this go to @jspricke @Wheedman
