### ISSUE TITLE
Show permission pop-up if location permission is revoked while app is closed

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#31]
This is how it looks on iOS:

<img width="302" alt="Screen Shot 2021-01-06 at 23 19 21" src="https://user-images.githubusercontent.com/1577223/103825683-9c620f80-5075-11eb-9a55-d76e451b6eee.png">

**Comment by Wheedman** [comment]
@v4lli  as we dscussed today in discord the user only will be notified via a pop-up that the last cached location will be used. 
Solved this in commit 6ba6a8cd08a21ab28671912c221ca3a6aef18a07
