### ISSUE TITLE
Disable zoom-on-start if location permission is rovoked while app is closed

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#32]
How to reproduce: Enable "Zoom on Start", close app, revoke location permissions, open app -> "Zoom after start" is still enabled.

This is how it looks on iOS:

<img width="272" alt="Screen Shot 2021-01-06 at 23 25 16" src="https://user-images.githubusercontent.com/1577223/103826076-6ffac300-5076-11eb-8d39-7e60c25c4307.png">

**Comment by Wheedman** [comment]
@v4lli  as we dscussed today in discord the user only will be notified via a pop-up that the last cached location will be used. 
Solved this in commit 6ba6a8cd08a21ab28671912c221ca3a6aef18a07
