### ISSUE TITLE
Native layerswitcher button

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#38]
Inject the following JS to open the layerswitcher: `window.openLayerswitcher();`

On iOS, the button(s) are hidden once the layerswitcher is opened. If a layer is selected, the frontend generates an event in that case (which requires integration into the JavascriptInterface-thing) which un-hides the button again on iOS, let me know which function to call if you need that. :)

**Comment by Wheedman** [comment]
Button is implemented.
