### ISSUE TITLE
"Did you know? meteocool has notifications"

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#50]
On iOS, after some time, this additional onboarding is shown to inform the user that meteocool has free & awesome notifications:

![simulator_screenshot_4766EBE1-F961-4B79-8632-098C5A6CB6DB](https://user-images.githubusercontent.com/1577223/108637633-c471ca80-748b-11eb-8641-abbd807fc1be.png)

**Comment by Wheedman** [comment]
Already solved in 043c01dec46773b6f640ca7fe67ae4bd1e448826
