### ISSUE TITLE
Explain "Details" setting somewhere

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#60]
Users are reporting that it's unclear what the "Details" settings switch does. Here's the explanation from iOS:

<img width="440" alt="Screen Shot 2021-03-28 at 14 33 15" src="https://user-images.githubusercontent.com/1577223/112752289-89a30b00-8fd2-11eb-87f5-733719424730.png">

<img width="453" alt="Screen Shot 2021-03-28 at 14 33 11" src="https://user-images.githubusercontent.com/1577223/112752293-8d369200-8fd2-11eb-82fb-657536528d53.png">

**Comment by Wheedman** [comment]
Solved in a2cc4c65b5ddae7725d9dbf7aa3ca610d45aed4d
