### ISSUE TITLE
Synchronize UI dark mode to system darkmode by setting 'prefers-color-scheme: dark' in webview

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#61]
![Screenshot_20210405_165244_com meteocool](https://user-images.githubusercontent.com/1577223/113591937-d7ec8580-9634-11eb-98b0-28e50df06e80.jpg)

The frontend implements a darkmode which is triggered through a media query ('prefers-color-scheme: dark') which already works on Desktop & iOS. Would be cool if the webview would set this property according to the system wide darkmode.

**Comment by Wheedman** [comment]
Solved in c90e92d65e4d38687849afa5c82c796307c7b5b8
