### ISSUE TITLE
Notifications are not disabled when confirming dialog with OK

### ISSUE THREAD

**Issue by v4lli** [meteocool/android#69]
<img width="412" alt="Screen Shot 2021-05-02 at 02 48 36" src="https://user-images.githubusercontent.com/1577223/116798553-e6717400-aaf0-11eb-8782-0eb6ab257bdf.png">

The popup is shown up on every app startup :///

**Comment by Wheedman** [comment]
Fixed in 182a829c88ec5b96b09b493263756a2dbe045696
